### ISSUE TITLE
Move animateOnSplice to a separate repositoty

### ISSUE THREAD

**Issue by timurnurutdinov** [marckrenn/framer-marcsOtherModules#1]
Have just tried animateOnSplice and it's awesome! Would you be so kind to create a separate repository to let us put a star and watch for future iterations?

**Comment by marckrenn** [comment]
Of course, glad you like it! 👍

Here you go: [animateOnSpline repo](https://github.com/marckrenn/framer-animateOnSpline/).

FYI: That Framer Modules link won't work right now.
